import { z } from "zod";
import { DraftUnit, type DraftUnitT } from "./display-question";

/**
 * Connector-safe representation of a draft unit.
 *
 * ChatGPT's connector validator does not correctly evaluate the `oneOf`
 * generated by the domain `DraftUnit` discriminated union. Keep the wire
 * schema flat, then restore the full domain invariants in the tool handler.
 */
const ConnectorDisplayQuestion = z
  .string()
  .min(10)
  .max(200)
  .describe("User-facing display question, ending in '?'.");

const ConnectorTemplateVariable = z.object({
  name: z
    .string()
    .min(1)
    .describe(
      "Name of one narrow, finite parameter such as a date, match, city, or candidate; do not use an open-ended event or outcome category.",
    ),
  values: z
    .array(z.string().min(1))
    .min(1)
    .describe(
      "Explicit closed set of concrete values. Every value and meaningful combination must share the same qualifying predicate, interpretation, settlement source, formula, procedure, methodology, and legal/compliance analysis.",
    ),
});

export const ConnectorDraftUnit = z
  .object({
    type: z
      .enum(["binary", "scalar", "categorical", "template"])
      .describe(
        "Forecast specification shape. Binary uses question; scalar and categorical use questions; template uses question and variables.",
      ),
    question: ConnectorDisplayQuestion.optional().describe(
      "The single Yes/No question for a binary forecast specification, or placeholder-bearing template question whose every allowed substitution preserves one settlement framework.",
    ),
    questions: z
      .array(ConnectorDisplayQuestion)
      .min(2)
      .optional()
      .describe(
        "The complete question set for a scalar or categorical forecast specification (at least two).",
      ),
    variables: z
      .array(ConnectorTemplateVariable)
      .min(1)
      .optional()
      .describe(
        "For a template, one entry per placeholder. Use only narrow finite parameters whose every allowed value and meaningful combination has the same settlement source, formula, procedure, methodology, interpretation, and legal/compliance analysis; otherwise draft separate units.",
      ),
  })
  .describe(
    "A forecast specification unit. Template placeholders must be narrow and finite; split cases that need a different qualifying rule, interpretation, source, settlement method, or legal/compliance analysis.",
  );

export type ConnectorDraftUnitT = z.infer<typeof ConnectorDraftUnit>;

/** Restore the discriminated-union invariants omitted from the wire schema. */
export function parseConnectorDraftUnit(unit: ConnectorDraftUnitT): DraftUnitT {
  return DraftUnit.parse(unit);
}
