import { z } from "zod";
import { DraftUnit, type DraftUnitT } from "./display-question";

/**
 * Connector-safe representation of a draft unit.
 *
 * ChatGPT's connector validator does not correctly evaluate the `oneOf`
 * generated by the domain `DraftUnit` discriminated union. Keep the wire
 * schema flat, then restore the full domain invariants in the tool handler.
 */
const ConnectorDisplayQuestion = z
  .string()
  .min(10)
  .max(200)
  .describe("User-facing display question, ending in '?'.");

const ConnectorTemplateVariable = z.object({
  name: z
    .string()
    .min(1)
    .describe(
      "Name of one narrow, finite parameter such as a date, match, city, or candidate; do not use an open-ended event or outcome category.",
    ),
  values: z
    .array(z.string().min(1))
    .min(1)
    .describe(
      "Explicit closed set of concrete values. Every value and meaningful combination must share the same qualifying predicate, interpretation, settlement source, formula, procedure, methodology, and legal/compliance analysis.",
    ),
});

export const ConnectorDraftUnit = z
  .object({
    type: z
      .enum([
        "binary",
        "template",
      ])
      .describe(
        "Forecast specification shape. Binary uses question; template uses question and variables.",
      ),
    question: ConnectorDisplayQuestion.optional().describe(
      "The single Yes/No question for a binary forecast specification or the placeholder-bearing question for a template.",
    ),
    variables: z
      .array(ConnectorTemplateVariable)
      .min(1)
      .optional()
      .describe(
        "One entry per placeholder for a template. Values may be scalar ranges or categorical outcomes only when all values share one settlement framework.",
      ),
  })
  .describe(
    "A binary or template forecast specification unit.",
  );

export type ConnectorDraftUnitT = z.infer<typeof ConnectorDraftUnit>;

/** Restore the discriminated-union invariants omitted from the wire schema. */
export function parseConnectorDraftUnit(unit: ConnectorDraftUnitT): DraftUnitT {
  return DraftUnit.parse(unit);
}
