import { z } from "zod";
import { DraftUnit, type DraftUnitT } from "../../src/schema/display-question";

/**
 * Connector-safe representation of a draft unit.
 *
 * ChatGPT's connector validator does not correctly evaluate the `oneOf`
 * generated by the domain `DraftUnit` discriminated union. Keep the wire
 * schema flat, then restore the full domain invariants in the tool handler.
 */
const ConnectorDisplayQuestion = z
  .string()
  .min(10)
  .max(200)
  .describe("Trader-facing display question, ending in '?'.");

const ConnectorTemplateVariable = z.object({
  name: z
    .string()
    .min(1)
    .describe("Placeholder name without the surrounding angle brackets."),
  values: z
    .array(z.string().min(1))
    .min(1)
    .describe("Allowed concrete values for this placeholder."),
});

export const ConnectorDraftUnit = z
  .object({
    type: z
      .enum(["binary", "scalar", "categorical", "template"])
      .describe(
        "Market shape. Binary uses question; scalar and categorical use questions; template uses question and variables.",
      ),
    question: ConnectorDisplayQuestion.optional().describe(
      "The single Yes/No question for a binary market, or placeholder-bearing question for a template market.",
    ),
    questions: z
      .array(ConnectorDisplayQuestion)
      .min(2)
      .optional()
      .describe(
        "The complete question set for a scalar or categorical market (at least two).",
      ),
    variables: z
      .array(ConnectorTemplateVariable)
      .min(1)
      .optional()
      .describe(
        "For a template market, one entry per angle-bracket placeholder in question.",
      ),
  })
  .describe(
    "A market unit. The server validates the required field for its market shape.",
  );

export type ConnectorDraftUnitT = z.infer<typeof ConnectorDraftUnit>;

/** Restore the discriminated-union invariants omitted from the wire schema. */
export function parseConnectorDraftUnit(unit: ConnectorDraftUnitT): DraftUnitT {
  return DraftUnit.parse(unit);
}
