import { z } from "zod";
import { DraftUnit, type DraftUnitT } from "../../src/schema/display-question";

/**
 * Connector-safe representation of a draft unit.
 *
 * ChatGPT's connector validator does not correctly evaluate the `oneOf`
 * generated by the domain `DraftUnit` discriminated union. Keep the wire
 * schema flat, then restore the full domain invariants in the tool handler.
 */
const ConnectorDisplayQuestion = z
  .string()
  .min(10)
  .max(200)
  .describe("Trader-facing display question, ending in '?'.");

export const ConnectorDraftUnit = z
  .object({
    type: z
      .enum(["binary", "scalar", "categorical"])
      .describe(
        "Market shape. Binary uses question; scalar and categorical use questions.",
      ),
    question: ConnectorDisplayQuestion.optional().describe(
      "The single Yes/No question for a binary market.",
    ),
    questions: z
      .array(ConnectorDisplayQuestion)
      .min(2)
      .optional()
      .describe(
        "The complete question set for a scalar or categorical market (at least two).",
      ),
  })
  .describe(
    "A market unit. The server validates the required field for its market shape.",
  );

export type ConnectorDraftUnitT = z.infer<typeof ConnectorDraftUnit>;

/** Restore the discriminated-union invariants omitted from the wire schema. */
export function parseConnectorDraftUnit(unit: ConnectorDraftUnitT): DraftUnitT {
  return DraftUnit.parse(unit);
}
